# -*- coding: utf-8 -*-
"""Urna

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhAT16qGtvVbv5ZrMUFye8G5LBfhyfCl
"""

# Aluno: Murilo Barbosa
# Curso: Analise e Desenvolvimento de Sistemas
# Diciplina: Construção de Algoritimos


eleitores = int(input("Digite o numero de eleitores: "))
print('''Candidato 1: Vincent Vega
Candidato 2: Jules Winnfield
Candidato 3: Marsellus Wallace''')
candidato1 = 0
candidato2 = 0
candidato3 = 0
voto = 0
maior = 0

while voto != eleitores:
  erro = 0
  escolha = int(input("Qual Candidato Você deseja votar: "))
  while escolha <= 0 or escolha >= 4:
    escolha = int(input("Digite uma opção valida: "))
    erro = erro + 1
    if erro == 4: 
      print("Quantidades de tentativas excedida, VOTO ANULADO.")
      break
  if escolha == 1:
    print("Você votou no candidato Vincent Vega") 
    candidato1 = candidato1 + 1
    voto = voto + 1
  elif escolha == 2:
    print("Você votou no candidato Jules Winnfield")
    candidato2 = candidato2 + 1
    voto = voto + 1
  elif escolha == 3:
    print("Você votou no candidato Marsellus Wallace")
    candidato3 = candidato3 + 1
    voto = voto + 1
candidato1 = (candidato1 * 100) / voto
candidato2 = (candidato2 * 100) / voto
candidato3 = (candidato3 * 100) / voto
print(f'''O candidato Vicent Vega teve {candidato1}%
O candidato Jules Winnfiel teve {candidato2}%
O candidato Marcellus Winnfield teve {candidato3}%''')
if candidato1 > candidato2 and candidato1 > candidato3:
   print(f'O ganhador é o Vicent Vega com {canidato1}%')
elif candidato2 > candidato1 and candidato2 > candidato3:
   print(f'O ganhador é o Jules Winnfield com {candidato2}%')
elif candidato3 > candidato1 and candadato3 > candidato2:
   print(f'O ganahdor é o Marcellus Wallace com {cadidato3}%')
elif candidato1 == candidato2:
   print(f'Os candidatos Vicent Vega e Jules Winnfield empataram com {candidato1}%')
elif candidato1 == candidato3:
   print(f'Os candidatos Vicent Vega e Marcellus Wallace emapatam com {candidato3}%')
elif candidato2 == candidato3:
   print(f'Os candidatos Jules Winnfield e Marcellus Wallace emapataram com {candidato2}%')
else:
   print(f'Os três candidatos empataram com {candidato1}%')**